spring:
  application:
    name: bank
  datasource:
    url: jdbc:mysql://localhost:3306/online-bank
    password: 0987
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username: bakaredavid007@gmail.com
    password: ixrocxtcvhprqkwk
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
