spring:
  config:
    activate:
      on-profile: "prod"
  datasource:
    url: "jdbc:mysql://portkeeperdatabase:3306/database"
    username: "bakare"
    password: 0987

keeper:
  message: "Welcome to PORTKEEPER App ...local prod Api"
  contactDetails:
    name: DAVID BAKARE - DB
  onCallSupport:
    - +(234)8 159 602 684

senderEmail: "bakaredavid007@gmail.com"
receiverEmail: "bakare@systemspecscomng.onmicrosoft.com"