spring:
  config:
    activate:
      on-profile: "dev"
  datasource:
    url: "jdbc:mysql://localhost:3306/portkeeper"
    username: "root"
    password: "0987"
    driver-class-name: "com.mysql.cj.jdbc.Driver"

keeper:
  message: "Welcome to PORTKEEPER App ...local dev Api"
  contactDetails:
    name: DAVID BAKARE - DB
  onCallSupport:
    - +(234)8 159 602 684
server:
  port: 8080

senderEmail: "bakaredavid007@gmail.com"
receiverEmail: "bakare@systemspecscomng.onmicrosoft.com"