spring:
  config:
    activate:
      on-profile: "mac"
  datasource:
    url: "jdbc:mysql://localhost:3306/portkeeper"
    username: "bakare"
    password: "0756abwmB$"
    driver-class-name: "com.mysql.cj.jdbc.Driver"

keeper:
  message: "Welcome to PORTKEEPER App ...local mac Api"
  contactDetails:
    name: DAVID BAKARE - DB
  onCallSupport:
    - +(234)8 159 602 684
server:
  port: 8081

senderEmail: "bakaredavid007@gmail.com"
receiverEmail: "bakare@systemspecscomng.onmicrosoft.com"